### ISSUE TITLE
Unable to send body in browser with openapi 3.0.0 spec

### ISSUE THREAD

**Issue by ACB1337** [swagger-api/swagger-js#1262]
I have defined my api using openapi 3.0.0 and then loaded it inside my browser like this:
`var replayClient = new SwaggerClient("/swagger/replay.json");`. But when I try to call this method:
~~~~
/login:
    post:
      tags: [user]
      operationId: login
      security: []
      description: Retrieve REST token
      requestBody:
        content: 
          application/json:
            schema:
              required:
                - username
                - password
              properties:
                username:
                  description: Your username for replay
                  type: string
                  example: test@example.com
                password:
                  description: Your password for replay
                  type: string
                  example: password
~~~~

like this:
`replayClient.client.apis.user.login({body: {username: "test", password: "test"}})`
or like this:
`replayClient.client.apis.user.login({username: "test", password: "test"})`

No body is sent to the server. I can even call the method without any args at all and it doesnt give me an error like with the petstore example.

**Comment by shockey** [comment]
hi @ACB1337!

`replayClient.client.apis.user.login({requestBody: {username: "test", password: "test"}})` should work, since you're using an OpenAPI 3.0 definition. We might need to document that better :smile:

**Comment by guillaumesmo** [comment]
That didn't work for me neither, although this seems to work 
replayClient.client.apis.user.login({}, {requestBody: {username: "test", password: "test"}}))

not sure if that's the expected behaviour

**Comment by shockey** [comment]
@guillaumesmo, yep, you're right, I misspoke. Apologies to you and @ACB1337 for that!

In light of this, I added some documentation for `requestBody` w/r/t the tags interface: https://github.com/swagger-api/swagger-js/pull/1270

That should resolve this, so I'm going to close for now. Feel free to reply with any outstanding concerns!

**Comment by Miruako** [comment]
Hi, @guillaumesmo @shockey . I tried the way you mentioned, but still not work. This is my api specification.
`"/users/data/filesWithCommits": {
      "post": {
        "x-controller-name": "GithubController",
        "x-operation-name": "fetchFileListWithCommits",
        "tags": [
          "GithubController"
        ],
        "responses": {
          "200": {
            "description": "Github files with commits",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/FetchFileListResponse"
                  }
                }
              }
            }
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/FetchFileListRequest"
              }
            }
          }
        },
        "operationId": "GithubController.fetchFileListWithCommits"
      }
    }
  }`
and I tried like this:
`IntegrationMicroService.GithubController.GithubController_getFileByCommit({ requestBody: { githubData: githubData } })`
and
`IntegrationMicroService.GithubController.GithubController_getFileByCommit({}, { requestBody: { githubData: githubData } })`
